add relationship doc
PrestaShopCorp/partner-devtools.prestashop.com pull request #12
Opened 2021-12-16 17:17 UTC by khanhmas

2021-12-17 09:48 UTC, TakeshiDaveau requested changes

2021-12-17 09:48 UTC, TakeshiDaveau commented on docs/3-relationships/README.md
> +**IMPORANT**: The `ownerUuid` is based on the `ownerEmail`, it means that if the `ownerEmail` has changed, the `ownerUuid` will also be changed.
Plutôt que `**IMPORANT**` tu peux utiliser

```
:::warning

:::
```

Ça créé une formattage plus visible.

---

>  The `ownerUuid` is based on the `ownerEmail`, it means that if the `ownerEmail` has changed, the `ownerUuid` will also be changed.

@GautierBoudeweel je me pose une question fonctionnelle sur cette phrase, est-ce que c'est possible (même manuellement) dans Account de changer son email de connexion mais en gardant le même utilisateur ? 

Là ça décrit le changement d'ownership d'une boutique

2021-12-17 09:48 UTC, TakeshiDaveau commented on docs/3-relationships/README.md
> +title: About relationships
je pense que je mettrais la partie relationship avant la partie développement / webhook, genre en `1-` parce que c'est le premier truc à comprendre avant de se lancer dans le dev

2021-12-17 09:48 UTC, TakeshiDaveau commented on docs/3-relationships/README.md
> +# ![](/assets/images/common/logo-condensed-sm.png) About RBM
ici je pense que tu peux remplacer RBM par billing

2021-12-17 09:48 UTC, TakeshiDaveau commented on docs/3-relationships/README.md
> +Relationship in RBM is a parent-child link between a "parent" customer and a "child" customer
ici je pense que tu peux remplacer RBM par billing

2021-12-17 09:48 UTC, TakeshiDaveau commented on docs/3-relationships/README.md
> +**IMPORANT**: The subscription is attached to the shop (child customer).
Pareil ici tu peux mettre: 

```
:::danger

:::
```

La doc https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers

2021-12-17 10:05 UTC, GautierBoudeweel commented on docs/3-relationships/README.md
> +**IMPORANT**: The `ownerUuid` is based on the `ownerEmail`, it means that if the `ownerEmail` has changed, the `ownerUuid` will also be changed.
C'est une feature qui est prévue au niveau de l'interface centralisée PrestaShop Accounts, on s'y attaque mi-janvier. Oui, il sera possible de changer d'email sans changer de UUID. Actuellement, on le fait manuellement sur demande par des scripts ... Pour détecter le changement d'ownership, la seul clé invariante sera l'uuid

2021-12-17 10:45 UTC, jmcollin approved these changes

2021-12-17 13:13 UTC, TakeshiDaveau commented on docs/3-relationships/README.md
> +**IMPORANT**: The `ownerUuid` is based on the `ownerEmail`, it means that if the `ownerEmail` has changed, the `ownerUuid` will also be changed.
Ok merci pour ta réponse.

Du coup @khanhmas peut-etre mets à jour pour dire qu'il y a 2 use case distinctes : changement d'email avec le même owner et changement d'owner (qui implique un changement d'email)

2021-12-20 14:43 UTC, TakeshiDaveau approved these changes

2021-12-20 15:18 UTC, merged