customer billing address updated
PrestaShopCorp/partner-devtools.prestashop.com pull request #13
Opened 2021-12-20 17:21 UTC by khanhmas

2021-12-21 07:58 UTC, TakeshiDaveau requested changes

2021-12-21 07:58 UTC, TakeshiDaveau commented on docs/3-webhook-events/README.md
> +* `customer-billing-address.updated`: Triggered when a customer billing address is updated
il vaut mieux faire une nouvelle section, parce que la payload est différente (on n'a que la billing address) et que c'est un autre type d'évènement le type `customer-billing-address` !== `customer`.

2021-12-21 18:09 UTC, TakeshiDaveau requested changes

2021-12-21 18:09 UTC, TakeshiDaveau commented on docs/3-webhook-events/README.md
> +  "eventType": "customer-billing-address.created",
ici je pense que ce n'est pas la bonne payload. Si tu regarde bien dans le [ticket](https://forge.prestashop.com/browse/OFF-402) j'ai mis la payload.

Elle est comme ça:

```
{
  "eventType": "customer.updated",
  "data": {
    "shopId": "7gftdLqMnSbtbuxhEwgafJkEMas1",
    "chargebeeCustomerId": "16CW0USXyu9Mu1xQF",
    "billingAddress": {
      "first_name": "David",
      "last_name": "BOUTON",
      "company": "LA FABRIQUE D ALIZE",
      "line1": "17 Impasse Alain Bombard",
      "city": "La roche sur yon",
      "country": "FR",
      "zip": "85000",
      "validation_status": "not_validated",
      "object": "billing_address"
    },
    "vatNumber": "95834084824",
    "module_id": "storecommanderps"
  },
```

On n'envoie pas le customer en entier. Il faudrait plutot mettre un lien vers les billing address dans la doc chargebee et faire aparaitre les autres champs dans le tableau : `shopId`, `chargebeeCustomerId`, `vatNumber`

2021-12-22 09:03 UTC, khanhmas commented on docs/3-webhook-events/README.md
> +  "eventType": "customer-billing-address.created",
le eventType est plutot c`ustomer-billing-address.updated`, non ?

2021-12-22 09:07 UTC, khanhmas commented on docs/3-webhook-events/README.md
> +  "eventType": "customer-billing-address.created",
mais c'est bizarre quand meme, les autres payloads contient le "customer"


aussi, dans le code, on envoie aussi le customer en entier

<img width="676" alt="Capture d’écran 2021-12-22 à 10 07 06" src="https://user-images.githubusercontent.com/8402110/147066685-a57cbce0-e5cd-4c1f-b5d8-5fde38405f43.png">

2021-12-22 09:49 UTC, TakeshiDaveau commented on docs/3-webhook-events/README.md
> +  "eventType": "customer-billing-address.created",
> le eventType est plutot customer-billing-address.updated, non ?

Oui je reprenais l'ancienne version


> dans le code, on envoie aussi le customer en entier

En fait c'est pas le plus important, le plus important c'est ce qu'on souhaite faire, dans l'idée moi ça me va d'envoyer le customer, mais il me semble que ce n'est pas ce qu'on avait convenu.

Mais moi ça ne me gêne pas qu'on mette le customer entier, mais ça fait plus de modification alors parce qu'il faut enlever billingAddress, vatNumber pour ne pas avoir de doublon. Ça veut dire aussi etre sur que rien ne dépend de ces infos (chez billing et chez d'autres squad)

2021-12-22 15:45 UTC, TakeshiDaveau requested changes

2021-12-22 15:45 UTC, TakeshiDaveau commented on docs/3-webhook-events/README.md
> +    "shopId": "7gftdLqMnSbtbuxhEwgafJkEMas1",
dernier micro retour, ici il ne faudrait pas mettre des vrais infos, donc pas le vrai shopId ni le vrai nom / prénom / adresse.
Ça c'est une vraie personne c'est pas ouf

2021-12-22 15:46 UTC, TakeshiDaveau approved these changes

2021-12-22 15:52 UTC, merged