add doc update quantity
PrestaShopCorp/partner-devtools.prestashop.com pull request #20
Opened 2022-01-18 15:32 UTC by khanhmas

2022-01-18 17:02 UTC, TakeshiDaveau requested changes

2022-01-18 17:02 UTC, TakeshiDaveau commented on docs/5-api/README.md
> +---
je mets mon commentaire ici parc que je ne sais pas trop où le mettre mais il me semble qu'il y avait l'ajout d'un module RBM (ou la modification de celui qui existe actuellement) pour pouvoir setter la quantity. Tu le fais dans une autre PR ?

2022-01-19 09:25 UTC, khanhmas commented on docs/5-api/README.md
> +---
je pense qu'on n'a pas besoin de creer un module directement dans ce repo parce que c'est un repo publique

ce que j'aime bien faire est que je build un module .zip et vous renvoyer via le channel slack ou le mets directement dans le ticket

2022-01-19 14:04 UTC, khanhmas commented on docs/5-api/README.md
> +| Param        | Type  | Description |
merci, je suis ce doc https://github.com/jamescooke/restapidocs/blob/master/examples/accounts/pk/put.md

2022-01-19 14:06 UTC, khanhmas commented on docs/5-api/README.md
> +| Param        | Type  | Description |
je pense qu'on n'a pas besoin de mentionner le term technique `UpdateQuantityDTO` dans la doc parce que ce qui interessent aux partenaires est le format du payload

2022-01-19 14:22 UTC, TakeshiDaveau requested changes

2022-01-19 14:22 UTC, TakeshiDaveau commented on docs/5-api/README.md
> +| Param        | Type  | Description |
En fait c'est pas forcément spécifier que c'est un DTO, mais c'est plutôt pour éviter d'avoir à répéter plusieurs fois cette structure si on en a besoin à plusieurs endroit.

Comme c'est fait dans openapi par exemple là on a :

```  
/shops/{shop_id}:
    post:
      deprecated: true
      operationId: CustomerController_createCustomer
      parameters:
        - name: shop_id
          in: path
          type: string
          required: true
          description: ''
        - name: body
          in: body
          required: true
          description: ''
          schema:
            '$ref': '#/definitions/CustomerDto'
      responses:
        200:
          description: ''

   ...
   
  CustomerDto:
    type: object
    properties:
      shop_id:
        type: string
        description: Shop id
        example: a281da2e-324b-4bad-b193-70df6d8b0120
      created_from_ip:
        type: string
      cf_owner_id:
        type: string
        description: Owner ID
        example: PdGxQmI3n1TumWSvOClg1rYORY82
      module:
        type: string
        description: Technical module name
        example: ps_metrics
    required:
    - shop_id
    - created_from_ip
    - cf_owner_id
    - module
```

L'objectif c'est pas tellement de dire qu'on utilise `CustomerDto`, le but c'est de ne pas avoir répéter la structure de `CustomerDto` plusieurs fois dans la doc.

Donc c'est pas mal de faire 2 parties : 
1. Descriptions des API avec des liens vers les models
2. description des liens
      

Le but c'est juste d'avoir moins de modifications à faire, comme quand on factorise le code

2022-01-19 14:22 UTC, TakeshiDaveau commented on docs/5-api/README.md
> +{
Ici tu répète la même chose que dans le tableau plus bas ou tu présente `action` et `quantity`, je ne pense pas que ce soit utile (et si on change on devra changer à 2 endroits).

Donc je dirais soit on utilise le tableau, soit on utilise ce payload constraints

2022-01-19 14:22 UTC, TakeshiDaveau commented on docs/5-api/README.md
> +`Authorization: <token>`
peut etre ici ajouter le genre d'erreur en retour quand on n'est pas authentifié, ça évite de devoir le répéter après pour chaque route

2022-01-19 14:23 UTC, TakeshiDaveau commented on docs/5-api/README.md
> +| Param        | Type  | Description |
Enfin à voir si c'est utile, mais c'est pour que tu comprenne mieux l'enjeu

2022-01-19 14:24 UTC, TakeshiDaveau commented on modules/rbm_example_stairstep/_dev/zip-module.js
> +const fs = require('fs');
je ne sais pas si c'est utile de dupliquer ça en plus il ne fonctionne pas ce script 😄

2022-01-19 14:40 UTC, khanhmas commented on docs/5-api/README.md
> +{
c'est pas une repetition, celui en bas est un exemple

2022-01-19 14:42 UTC, khanhmas commented on docs/5-api/README.md
> +{
ok, je laisse le tableau alors

2022-01-19 14:44 UTC, khanhmas commented on docs/5-api/README.md
> +{
pour moi, le payload constraints est comm un "big picture", pour plus de details, on regarde le tableau

2022-01-20 08:47 UTC, TakeshiDaveau approved these changes

2022-01-20 09:34 UTC, merged