Off 318/feature/rbm ci
PrestaShopCorp/partner-devtools.prestashop.com pull request #26
Opened 2022-02-07 13:48 UTC by khanhmas

2022-02-14 09:37 UTC, jmcollin commented on .github/workflows/rbm_module_build.yaml
> +      env_name: prod
plutôt `stable` à la place de `prod` pour respecter les [environements](https://github.com/PrestaShopCorp/billing.prestashop.com/tree/main/.cloud#environment-variables)

2022-02-14 09:38 UTC, jmcollin commented on .github/workflows/rbm_module_build.yaml
> +      env_name: prod
plutôt `stable` à la place de `prod` pour respecter les [environements](https://github.com/PrestaShopCorp/billing.prestashop.com/tree/main/.cloud#environment-variables)

2022-02-14 09:40 UTC, jmcollin requested changes
Comme indiquer dans les commentaires, il serai mieux de respecter la sémantique `stable` à la place de `prod` pour respecter les [environements](https://github.com/PrestaShopCorp/billing.prestashop.com/tree/main/.cloud#environment-variables)

2022-02-14 10:16 UTC, jmcollin approved these changes

2022-02-14 14:22 UTC, TakeshiDaveau commented on .github/workflows/rbm_module_build.yaml
> +      env_name: prod
Je suis pour respecter ce qui est en place ouai.

---

Après sur la sémantique de base alpha / stable je la trouve pas raccord avec ce qu'on fait. Ici on parle bel et bien d'environnement : integration, preprod, production et pas de version de code : alpha, beta, stable.

2022-02-14 14:29 UTC, TakeshiDaveau requested changes

2022-02-14 14:29 UTC, TakeshiDaveau commented on .github/actions/install-build-dependencies/action.yaml
> +description: Install php and js dependencies
il manque la mention de dire que ça compile le JS aussi

2022-02-14 14:29 UTC, TakeshiDaveau commented on .github/workflows/create_release.yaml
> +      # - main
faudra bien penser à modifier ça avant de merge

2022-02-14 14:29 UTC, TakeshiDaveau commented on .github/workflows/create_release.yaml
> +        uses: toolmantim/release-drafter@v5
du coup pourquoi tu as utilisé `toolmantim/release-drafter@v5`  plutôt que `release-drafter/release-drafter@v5` ? (ça me gêne pas du tout c'est pour savoir)

2022-02-14 14:29 UTC, TakeshiDaveau commented on .github/workflows/rbm_module_build.yaml
> +  publish_release_prod:
si tu peux mettre un petit espace au dessus pour bien démarquer la partie de build et la partie de release.

2022-02-14 14:29 UTC, TakeshiDaveau commented on .github/workflows/rbm_module_build.yaml
> +      - name: Zip
peut-être que pour cette step de zip ça vaudrait le coup de créer une action

2022-02-14 14:30 UTC, khanhmas commented on .github/workflows/create_release.yaml
> +        uses: toolmantim/release-drafter@v5
ah, parce que j'ai vu que les autres repos utilisent toolmantim/release-drafter@v5, apres l'avoir teste, je trouve que ca fonctionne toujours, du coup, je le laisse :)

2022-02-15 09:54 UTC, TakeshiDaveau approved these changes

2022-02-15 09:55 UTC, merged