build(tunnel): Add PrestaShop http tunnel
PrestaShopCorp/partner-devtools.prestashop.com pull request #3
Opened 2021-11-02 15:53 UTC by jmcollin

Allow to use PrestaShop http tunnel

2022-04-28 17:09 UTC, TakeshiDaveau requested changes

2022-04-28 17:09 UTC, TakeshiDaveau commented on README.md
> +### Environment variables
je mettrais cette partie là avant la partie `#### Custom install` parce que le commun des mortels vont plus chercher cette info que la partie custome install qui est plus pour les barbus 😄

2022-04-28 17:10 UTC, TakeshiDaveau commented
J'ai fait une tite review, rien de bien méchant, demain je test sur mon poste et j'envoie la PR à Store Commander pour qu'uils testent avant qu'on puisse merge.

2022-04-29 08:30 UTC, maximesimoncelli commented
Il faudra peut-être enlever les pipefail, ils me font des unbound variables.

2022-04-29 08:38 UTC, maximesimoncelli requested changes
Enlever les pipefails ou faire en sorte qu'ils ne créent pas d'unbound variables.

2022-05-02 09:08 UTC, TakeshiDaveau approved these changes

2022-05-02 09:31 UTC, jmcollin commented on README.md
> +### Environment variables
yes ok

2022-05-02 09:33 UTC, jmcollin commented on README.md
> +* ``TUNNEL_DOMAIN`` - Define tunnel domain (default value: localtunnel.distribution.prestashop.net)
Si tu parles du `TUNNEL_DOMAIN`, il faut laisser la possibilité aux personnes de pouvoir host leurs propres version de localtunnel

Par ailleurs, le reste du script à besoin de cette var pour pouvoir gérer les urls (récupération & mise à jour si besoin)

2022-05-02 09:55 UTC, maximesimoncelli approved these changes

2022-05-12 12:18 UTC, merged